services:
  - type: web
    name: painel-precos
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py --server.port=8000 --server.enableCORS=false
